export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Service-1',
    headline: 'College-Space',
    description: 'A place where students and teachers can easily exchange resources and notifications.',
    buttonLabel: 'Back To Top',
    imgStart: false,
    img: require('../../images/svg-2.svg').default,
    alt: 'Rocket',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Service-2',
    headline: 'Student Blog',
    description: 'A place where like minded individuals and communities can interact with each other.',
    buttonLabel: 'Back To Top',
    imgStart: true,
    img: require('../../images/svg-3.svg').default,
    alt: 'Planet',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Service-3',
    headline: 'Food Delivery',
    description: 'Hungry? We have got you covered, click here for freshly delivered food.',
    buttonLabel: 'Back To Top',
    imgStart: false,
    img: require('../../images/svg-6.svg').default,
    alt: 'Alien',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjFour = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Service-4',
    headline: 'Bits-Shop',
    description: 'A place where you can sell tickets for events,merchandise and whatever you wish for.',
    buttonLabel: 'Back To Top',
    imgStart: false,
    img: require('../../images/svg-4.svg').default,
    alt: 'Alien',
    dark: false,
    primary: false,
    darkText: true,
};